### ISSUE TITLE
Link Docker Hub images to Dockerfiles

### ISSUE THREAD

**Issue by heitortsergent** [cloudfoundry-incubator/diego-dockerfiles#2]
It would be great if we could have links between the Docker Hub images (for example: https://registry.hub.docker.com/u/cloudfoundry/warden-ci/) and their Dockerfiles. If not the automated build sidebar link, at least a reference to it in the full description.

**Comment by ematpl** [comment]
Thanks for the suggestion, @heitortsergent! I'm going to close and then immediately re-open this issue so that a story is generated in the Diego team tracker.

Best,
Eric, CF Runtime Diego PM

**Comment by ematpl** [comment]
Thanks, @heitortsergent. We've now added the Dockerfile link to those Docker Hub image pages for the images that the Diego team is actively maintaining (golang-ci, inigo-ci, diego-docker-app, diego-docker-app-custom). The Diego team no longer uses the remaining images in this repo (the stacks; warden-ci; with-volume), but the Garden team may still be using the latter two images. We have left those obsolete images alone for now and have a follow-on story (https://www.pivotaltracker.com/story/show/117554275) to transfer them to the Garden team or to delete them.

Best,
Eric

**Comment by heitortsergent** [comment]
Thanks for the update @ematpl :D
